# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ActionUpdate(str, Enum):
    """
    ActionUpdate
    """

    """
    allowed enum values
    """
    ADD = 'Add'
    REPLACE = 'Replace'
    TOREMOVE = 'ToRemove'
    CLEARALL = 'ClearAll'

    @classmethod
    def from_json(cls, json_str: str) -> ActionUpdate:
        """Create an instance of ActionUpdate from a JSON string"""
        return ActionUpdate(json.loads(json_str))


