# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class BackgroundJobType(str, Enum):
    """
    BackgroundJobType
    """

    """
    allowed enum values
    """
    EXPORTXLSXTESTRESULTSBYTESTPLAN = 'ExportXlsxTestResultsByTestPlan'
    EXPORTXLSXWORKITEMSBYPROJECT = 'ExportXlsxWorkItemsByProject'
    EXPORTXLSXTESTPOINTSBYTESTPLAN = 'ExportXlsxTestPointsByTestPlan'
    EXPORTJSONPROJECT = 'ExportJsonProject'
    EXPORTZIPPROJECT = 'ExportZipProject'
    EXPORTJSONPROJECTWITHTESTPLANS = 'ExportJsonProjectWithTestPlans'
    EXPORTZIPPROJECTWITHTESTPLANS = 'ExportZipProjectWithTestPlans'
    IMPORTJSONPROJECT = 'ImportJsonProject'
    IMPORTZIPPROJECT = 'ImportZipProject'
    IMPORTXLSXPROJECT = 'ImportXlsxProject'
    IMPORTTESTRAILXMLPROJECT = 'ImportTestRailXmlProject'
    PURGEPROJECT = 'PurgeProject'
    EXPORTPROJECTS = 'ExportProjects'
    IMPORTPROJECTS = 'ImportProjects'
    PURGEENTITIES = 'PurgeEntities'
    DELETECOMPLETEDJOBS = 'DeleteCompletedJobs'

    @classmethod
    def from_json(cls, json_str: str) -> BackgroundJobType:
        """Create an instance of BackgroundJobType from a JSON string"""
        return BackgroundJobType(json.loads(json_str))


