# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class StringChangedFieldWithDiffsViewModel(BaseModel):
    """
    StringChangedFieldWithDiffsViewModel
    """
    diff_value: Optional[StrictStr] = Field(default=None, alias="diffValue")
    old_value: Optional[StrictStr] = Field(default=None, alias="oldValue")
    new_value: Optional[StrictStr] = Field(default=None, alias="newValue")
    __properties = ["diffValue", "oldValue", "newValue"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StringChangedFieldWithDiffsViewModel:
        """Create an instance of StringChangedFieldWithDiffsViewModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if diff_value (nullable) is None
        # and __fields_set__ contains the field
        if self.diff_value is None and "diff_value" in self.__fields_set__:
            _dict['diffValue'] = None

        # set to None if old_value (nullable) is None
        # and __fields_set__ contains the field
        if self.old_value is None and "old_value" in self.__fields_set__:
            _dict['oldValue'] = None

        # set to None if new_value (nullable) is None
        # and __fields_set__ contains the field
        if self.new_value is None and "new_value" in self.__fields_set__:
            _dict['newValue'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StringChangedFieldWithDiffsViewModel:
        """Create an instance of StringChangedFieldWithDiffsViewModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StringChangedFieldWithDiffsViewModel.parse_obj(obj)

        _obj = StringChangedFieldWithDiffsViewModel.parse_obj({
            "diff_value": obj.get("diffValue"),
            "old_value": obj.get("oldValue"),
            "new_value": obj.get("newValue")
        })
        return _obj


