# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr, constr

class WorkItemCommentPostModel(BaseModel):
    """
    WorkItemCommentPostModel
    """
    text: constr(strict=True, max_length=1024, min_length=1) = Field(...)
    work_item_id: StrictStr = Field(default=..., alias="workItemId")
    __properties = ["text", "workItemId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> WorkItemCommentPostModel:
        """Create an instance of WorkItemCommentPostModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> WorkItemCommentPostModel:
        """Create an instance of WorkItemCommentPostModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return WorkItemCommentPostModel.parse_obj(obj)

        _obj = WorkItemCommentPostModel.parse_obj({
            "text": obj.get("text"),
            "work_item_id": obj.get("workItemId")
        })
        return _obj


