"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import testit_api_client
from testit_api_client.model.auto_test_change_view_model import AutoTestChangeViewModel


class TestAutoTestChangeViewModel(unittest.TestCase):
    """AutoTestChangeViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAutoTestChangeViewModel(self):
        """Test AutoTestChangeViewModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AutoTestChangeViewModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
