"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import testit_api_client
from testit_api_client.model.custom_attribute_types_enum import CustomAttributeTypesEnum
globals()['CustomAttributeTypesEnum'] = CustomAttributeTypesEnum
from testit_api_client.model.custom_attribute_template_search_query_model import CustomAttributeTemplateSearchQueryModel


class TestCustomAttributeTemplateSearchQueryModel(unittest.TestCase):
    """CustomAttributeTemplateSearchQueryModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomAttributeTemplateSearchQueryModel(self):
        """Test CustomAttributeTemplateSearchQueryModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomAttributeTemplateSearchQueryModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
