"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import testit_api_client
from testit_api_client.api.webhooks_logs_api import WebhooksLogsApi  # noqa: E501


class TestWebhooksLogsApi(unittest.TestCase):
    """WebhooksLogsApi unit test stubs"""

    def setUp(self):
        self.api = WebhooksLogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_webhooks_logs_get(self):
        """Test case for api_v2_webhooks_logs_get

        """
        pass

    def test_api_v2_webhooks_logs_id_delete(self):
        """Test case for api_v2_webhooks_logs_id_delete

        """
        pass

    def test_api_v2_webhooks_logs_id_get(self):
        """Test case for api_v2_webhooks_logs_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
