"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import testit_api_client
from testit_api_client.api.custom_attribute_templates_api import CustomAttributeTemplatesApi  # noqa: E501


class TestCustomAttributeTemplatesApi(unittest.TestCase):
    """CustomAttributeTemplatesApi unit test stubs"""

    def setUp(self):
        self.api = CustomAttributeTemplatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_custom_attributes_templates_id_custom_attributes_exclude_post(self):
        """Test case for api_v2_custom_attributes_templates_id_custom_attributes_exclude_post

        Exclude CustomAttributes from CustomAttributeTemplate  # noqa: E501
        """
        pass

    def test_api_v2_custom_attributes_templates_id_custom_attributes_include_post(self):
        """Test case for api_v2_custom_attributes_templates_id_custom_attributes_include_post

        Include CustomAttributes to CustomAttributeTemplate  # noqa: E501
        """
        pass

    def test_api_v2_custom_attributes_templates_id_delete(self):
        """Test case for api_v2_custom_attributes_templates_id_delete

        Delete CustomAttributeTemplate  # noqa: E501
        """
        pass

    def test_api_v2_custom_attributes_templates_id_get(self):
        """Test case for api_v2_custom_attributes_templates_id_get

        Get CustomAttributeTemplate by ID  # noqa: E501
        """
        pass

    def test_api_v2_custom_attributes_templates_name_get(self):
        """Test case for api_v2_custom_attributes_templates_name_get

        Get CustomAttributeTemplate by name  # noqa: E501
        """
        pass

    def test_api_v2_custom_attributes_templates_post(self):
        """Test case for api_v2_custom_attributes_templates_post

        Create CustomAttributeTemplate  # noqa: E501
        """
        pass

    def test_api_v2_custom_attributes_templates_put(self):
        """Test case for api_v2_custom_attributes_templates_put

        Update CustomAttributeTemplate  # noqa: E501
        """
        pass

    def test_api_v2_custom_attributes_templates_search_post(self):
        """Test case for api_v2_custom_attributes_templates_search_post

        Search CustomAttributeTemplates  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
