"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import testit_api_client
from testit_api_client.model.work_item_extraction_model import WorkItemExtractionModel


class TestWorkItemExtractionModel(unittest.TestCase):
    """WorkItemExtractionModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkItemExtractionModel(self):
        """Test WorkItemExtractionModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkItemExtractionModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
