"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import testit_api_client
from testit_api_client.model.attachment_change_view_model import AttachmentChangeViewModel
globals()['AttachmentChangeViewModel'] = AttachmentChangeViewModel
from testit_api_client.model.attachment_change_view_model_array_work_item_changed_field_view_model import AttachmentChangeViewModelArrayWorkItemChangedFieldViewModel


class TestAttachmentChangeViewModelArrayWorkItemChangedFieldViewModel(unittest.TestCase):
    """AttachmentChangeViewModelArrayWorkItemChangedFieldViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttachmentChangeViewModelArrayWorkItemChangedFieldViewModel(self):
        """Test AttachmentChangeViewModelArrayWorkItemChangedFieldViewModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttachmentChangeViewModelArrayWorkItemChangedFieldViewModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
