"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import testit_api_client
from testit_api_client.api.projects_api import ProjectsApi  # noqa: E501


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_projects_id_custom_attribute_templates_template_id_delete(self):
        """Test case for api_v2_projects_id_custom_attribute_templates_template_id_delete

        Delete CustomAttributeTemplate from Project  # noqa: E501
        """
        pass

    def test_api_v2_projects_id_custom_attribute_templates_template_id_post(self):
        """Test case for api_v2_projects_id_custom_attribute_templates_template_id_post

        Add CustomAttributeTemplate to Project  # noqa: E501
        """
        pass

    def test_api_v2_projects_id_failure_classes_get(self):
        """Test case for api_v2_projects_id_failure_classes_get

        Get Project FailureClasses  # noqa: E501
        """
        pass

    def test_api_v2_projects_id_favorite_put(self):
        """Test case for api_v2_projects_id_favorite_put

        Mark Project as favorite  # noqa: E501
        """
        pass

    def test_api_v2_projects_id_filters_get(self):
        """Test case for api_v2_projects_id_filters_get

        Get Project filters  # noqa: E501
        """
        pass

    def test_api_v2_projects_id_test_plans_analytics_get(self):
        """Test case for api_v2_projects_id_test_plans_analytics_get

        Get TestPlans analytics  # noqa: E501
        """
        pass

    def test_api_v2_projects_id_test_plans_search_post(self):
        """Test case for api_v2_projects_id_test_plans_search_post

        Get Project TestPlans with analytics  # noqa: E501
        """
        pass

    def test_api_v2_projects_id_test_runs_active_get(self):
        """Test case for api_v2_projects_id_test_runs_active_get

        Get active Project TestRuns  # noqa: E501
        """
        pass

    def test_api_v2_projects_id_test_runs_full_get(self):
        """Test case for api_v2_projects_id_test_runs_full_get

        Get Project TestRuns full models  # noqa: E501
        """
        pass

    def test_api_v2_projects_id_work_items_tags_get(self):
        """Test case for api_v2_projects_id_work_items_tags_get

        Get WorkItems Tags  # noqa: E501
        """
        pass

    def test_api_v2_projects_search_post(self):
        """Test case for api_v2_projects_search_post

        """
        pass

    def test_call_import(self):
        """Test case for call_import

        Import project from JSON file  # noqa: E501
        """
        pass

    def test_create_custom_attribute_test_plan_project_relations(self):
        """Test case for create_custom_attribute_test_plan_project_relations

        Add attributes to project's test plans  # noqa: E501
        """
        pass

    def test_create_project(self):
        """Test case for create_project

        Create project  # noqa: E501
        """
        pass

    def test_create_projects_attribute(self):
        """Test case for create_projects_attribute

        Create project attribute  # noqa: E501
        """
        pass

    def test_delete_custom_attribute_test_plan_project_relations(self):
        """Test case for delete_custom_attribute_test_plan_project_relations

        Delete attribute from project's test plans  # noqa: E501
        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        Delete project  # noqa: E501
        """
        pass

    def test_delete_project_auto_tests(self):
        """Test case for delete_project_auto_tests

        Delete project  # noqa: E501
        """
        pass

    def test_delete_projects_attribute(self):
        """Test case for delete_projects_attribute

        Delete project attribute  # noqa: E501
        """
        pass

    def test_export(self):
        """Test case for export

        Export project as JSON file  # noqa: E501
        """
        pass

    def test_export_with_test_plans_and_configurations(self):
        """Test case for export_with_test_plans_and_configurations

        Export project with test plans, test suites and test points as JSON file  # noqa: E501
        """
        pass

    def test_get_all_projects(self):
        """Test case for get_all_projects

        Get all projects  # noqa: E501
        """
        pass

    def test_get_attribute_by_project_id(self):
        """Test case for get_attribute_by_project_id

        Get project attribute  # noqa: E501
        """
        pass

    def test_get_attributes_by_project_id(self):
        """Test case for get_attributes_by_project_id

        Get project attributes  # noqa: E501
        """
        pass

    def test_get_auto_tests_namespaces(self):
        """Test case for get_auto_tests_namespaces

        Get namespaces of autotests in project  # noqa: E501
        """
        pass

    def test_get_configurations_by_project_id(self):
        """Test case for get_configurations_by_project_id

        Get project configurations  # noqa: E501
        """
        pass

    def test_get_custom_attribute_test_plan_project_relations(self):
        """Test case for get_custom_attribute_test_plan_project_relations

        Get project's test plan attributes  # noqa: E501
        """
        pass

    def test_get_project_by_id(self):
        """Test case for get_project_by_id

        Get project by ID  # noqa: E501
        """
        pass

    def test_get_sections_by_project_id(self):
        """Test case for get_sections_by_project_id

        Get project sections  # noqa: E501
        """
        pass

    def test_get_test_plans_by_project_id(self):
        """Test case for get_test_plans_by_project_id

        Get project test plans  # noqa: E501
        """
        pass

    def test_get_test_runs_by_project_id(self):
        """Test case for get_test_runs_by_project_id

        Get project test runs  # noqa: E501
        """
        pass

    def test_get_work_items_by_project_id(self):
        """Test case for get_work_items_by_project_id

        Get project work items  # noqa: E501
        """
        pass

    def test_import_to_existing_project(self):
        """Test case for import_to_existing_project

        Import project from JSON file into existing project  # noqa: E501
        """
        pass

    def test_restore_project(self):
        """Test case for restore_project

        Restore project  # noqa: E501
        """
        pass

    def test_update_custom_attribute_test_plan_project_relations(self):
        """Test case for update_custom_attribute_test_plan_project_relations

        Update attribute of project's test plans  # noqa: E501
        """
        pass

    def test_update_project(self):
        """Test case for update_project

        Update project  # noqa: E501
        """
        pass

    def test_update_projects_attribute(self):
        """Test case for update_projects_attribute

        Update project attribute  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
