"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import testit_api_client
from testit_api_client.model.date_time_range_selector_model import DateTimeRangeSelectorModel
from testit_api_client.model.test_run_state_type_model import TestRunStateTypeModel
globals()['DateTimeRangeSelectorModel'] = DateTimeRangeSelectorModel
globals()['TestRunStateTypeModel'] = TestRunStateTypeModel
from testit_api_client.model.test_run_search_query_model import TestRunSearchQueryModel


class TestTestRunSearchQueryModel(unittest.TestCase):
    """TestRunSearchQueryModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestRunSearchQueryModel(self):
        """Test TestRunSearchQueryModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TestRunSearchQueryModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
