"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import testit_api_client
from testit_api_client.model.label_short_model import LabelShortModel


class TestLabelShortModel(unittest.TestCase):
    """LabelShortModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLabelShortModel(self):
        """Test LabelShortModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LabelShortModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
