"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import testit_api_client
from testit_api_client.model.parameter_put_model import ParameterPutModel


class TestParameterPutModel(unittest.TestCase):
    """ParameterPutModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParameterPutModel(self):
        """Test ParameterPutModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParameterPutModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
