"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import testit_api_client
from testit_api_client.model.custom_attribute_option_model import CustomAttributeOptionModel
from testit_api_client.model.custom_attribute_types_enum import CustomAttributeTypesEnum
globals()['CustomAttributeOptionModel'] = CustomAttributeOptionModel
globals()['CustomAttributeTypesEnum'] = CustomAttributeTypesEnum
from testit_api_client.model.custom_attribute_update_model import CustomAttributeUpdateModel


class TestCustomAttributeUpdateModel(unittest.TestCase):
    """CustomAttributeUpdateModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomAttributeUpdateModel(self):
        """Test CustomAttributeUpdateModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomAttributeUpdateModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
