"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import testit_api_client
from testit_api_client.model.user_rank_model import UserRankModel


class TestUserRankModel(unittest.TestCase):
    """UserRankModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserRankModel(self):
        """Test UserRankModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserRankModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
