"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import testit_api_client
from testit_api_client.model.date_time_range_selector_model import DateTimeRangeSelectorModel
from testit_api_client.model.int64_range_selector_model import Int64RangeSelectorModel
from testit_api_client.model.test_point_status import TestPointStatus
from testit_api_client.model.work_item_priority_model import WorkItemPriorityModel
globals()['DateTimeRangeSelectorModel'] = DateTimeRangeSelectorModel
globals()['Int64RangeSelectorModel'] = Int64RangeSelectorModel
globals()['TestPointStatus'] = TestPointStatus
globals()['WorkItemPriorityModel'] = WorkItemPriorityModel
from testit_api_client.model.test_point_select_model import TestPointSelectModel


class TestTestPointSelectModel(unittest.TestCase):
    """TestPointSelectModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestPointSelectModel(self):
        """Test TestPointSelectModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TestPointSelectModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
