name: Check build like on publish

on:
  - pull_request


permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: Check version
        run: |
          VERSION=$(grep -oP 'VERSION\s*=\s*"\K[^"]+' setup.py)
          python .version_check/check.py $VERSION

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --upgrade
          pip install build

      - name: Build package
        run: python -m build -s
